Memory parsing
GlowLimeGames/LettersToReid pull request #16
Opened 2017-03-04 18:20 UTC by anishapai

Retrieve memories with ID number.

2017-03-04 18:22 UTC, imann24 commented on Assets/Scripts/TXT/MemoriesParser.cs
> +    public String getMemory(int id) {
I think it would be faster if this used a dictionary lookup: https://msdn.microsoft.com/en-us/library/xfhwa508(v=vs.110).aspx

2017-03-04 18:22 UTC, imann24 commented on Assets/Scripts/TXT/MemoryGroup.cs
> +    public Memory[] mmrs;
Should use a dictionary backing structure

2017-03-04 18:22 UTC, imann24 requested changes
Overall very solid logic! Lookup should use a Dictionary instead of an Array (improves lookup time from O(n) to O(1)

2017-03-04 19:34 UTC, anishapai commented on Assets/Scripts/TXT/MemoriesParser.cs
> +    public String getMemory(int id) {
@imann24 Made the changes! Just realised sourcetree is logged into your account, so maybe you didn't get notified of the pull request.

2017-03-05 17:45 UTC, imann24 commented on Assets/Scripts/TXT/MemoriesParser.cs
> +    public String getMemory(int id) {
Nice! Thanks for the bump.

2017-03-05 17:45 UTC, merged

2017-03-05 20:24 UTC, imann24 commented on Assets/Scripts/TXT/MemoriesParser.cs
> +    public String getMemory(int id) {
Also feel free to logout of my account so commit show as you